In [3]:
import scipy.stats as stats

In [4]:
stats.binom.pmf(2, n=5, p=0.1)

np.float64(0.07289999999999992)

In [5]:
stats.binom.cdf(2, n=5, p=0.1)

np.float64(0.99144)

In [6]:
stats.binom.pmf(0, n=200, p=0.02)

np.float64(0.017587946605721567)

In [8]:
stats.poisson.rvs(2, size=100)

array([2, 1, 3, 3, 2, 2, 3, 3, 1, 1, 2, 2, 3, 0, 5, 2, 3, 3, 1, 1, 5, 0,
       2, 1, 2, 0, 0, 4, 1, 2, 4, 1, 1, 2, 3, 3, 1, 2, 4, 3, 2, 3, 3, 1,
       4, 4, 2, 3, 0, 1, 1, 0, 3, 2, 2, 2, 3, 0, 4, 3, 1, 3, 2, 2, 2, 2,
       1, 1, 3, 1, 3, 4, 3, 1, 6, 3, 1, 1, 5, 1, 1, 2, 2, 1, 1, 1, 0, 5,
       6, 0, 1, 3, 3, 1, 2, 6, 1, 2, 0, 1])

In [11]:
stats.expon.rvs(0.2, size=100)

array([1.73778086, 1.21907357, 1.734888  , 1.92187995, 1.15835426,
       0.86912422, 0.58481205, 0.50980739, 1.84469747, 3.58964848,
       0.24618427, 1.2647035 , 1.72321691, 0.25263912, 1.1547353 ,
       2.36892752, 0.27685739, 0.68539891, 0.24099654, 1.08742745,
       0.9523341 , 0.64993722, 1.38209684, 0.21740306, 0.21032159,
       0.47975181, 1.76979205, 0.82641836, 0.88204313, 0.22233372,
       6.202089  , 0.84113464, 0.49285137, 1.92683616, 0.41020025,
       0.38141035, 0.22807426, 0.59633482, 0.23036762, 0.57782158,
       0.38466969, 0.20502242, 1.8347121 , 1.75350983, 1.15199068,
       2.48977698, 0.27819125, 0.51576558, 0.73284188, 1.7169695 ,
       0.93199286, 0.75852497, 0.70681021, 1.06464587, 1.06139053,
       1.68422755, 0.89470568, 0.88557513, 0.36820362, 2.56016276,
       1.53679641, 0.94260661, 2.85246172, 1.52518214, 0.49073161,
       0.23947843, 1.18198034, 2.15280461, 3.58648222, 0.3658864 ,
       1.63356542, 0.52149573, 1.96350963, 0.94279073, 2.05597

In [14]:
stats.weibull_min.rvs(1.5, scale=5000, size=100)

array([ 3207.91158982, 10988.94057462,  9942.89366066,  3296.3285822 ,
         561.05827915,  2423.56557192,  6334.66305559,  2547.8497772 ,
        1434.61566117,   857.24021368,  1708.41008771,  7703.30556274,
        2091.28646383,  7673.01573181,  1125.74152458, 12310.09953543,
        7552.36487574,  1093.74081878,  4999.09443582,  1152.06605154,
        1733.51202572,    41.39069352,  2746.81004689,  4484.71143023,
        4206.74534728,  4143.98225856,  5526.43062539,  7814.05984751,
        3335.09363614,  1623.63763467,  3916.53566501,  6076.29018331,
        4242.8032391 ,  4622.23920015,   835.06905201,  1602.47824018,
        7909.57084152,  3070.87691302,  3443.61711428,  6475.90060808,
        4188.88847791,  2952.93789933,  6236.01378124,  6446.34077152,
        5424.58043733,  2627.71770607,  1987.55569993,  1314.87961524,
         965.89268685,  4396.78650418,  3747.47379565,  4345.40014836,
        3841.881978  ,  1255.4274761 ,  2983.20990826,  1414.02237648,
      